a = float(input("Nilai a :"))
b = float(input("Nilai b :"))
i = float(input("Nilai i :"))
j = float(input("Nilai j :"))
x = float(input("Nilai x :"))
y = float(input("Nilai y :"))
hasil = (a-b)*(i/j)-(x+y)
print ("Hasil {:.3f}".format(hasil))