input("Nama                 :")
input("Nim                  :")
input("Kelas Pararel        :")
input("Tempat/Tanggal Lahir :")
input("Alamat               :")
input("Hobby                :")
input("No. HP               :")